# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ContactRealmLive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContactRealmLive
  pod 'RealmSwift'

  target 'ContactRealmLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContactRealmLiveUITests' do
    # Pods for testing
  end

end
